#!/bin/bash

cmake --build build --target Xerxes

fs_list=(1 16 66 256)
memcnt_list=(1 2 4 8)
ratio_list=("0.01" "0.25" "0.33" "0.5" "0.66" "0.75" "1")

# memcnt_list=(2)
# ratio_list=("0.5")

for fs in ${fs_list[@]}; do
    for memcnt in ${memcnt_list[@]}; do
        for ratio in ${ratio_list[@]}; do
            build/Xerxes $fs $memcnt $ratio
        done
    done
done
