ep_num = 1
rw_ratio = 0.1
max_clock = 1000000
clock_granu = 10
log_name = "output/try.csv"

[requester]
issue_delay = 0
burst_size = 1
block_size = 4096
q_capacity = 16
cache_capacity = 8192
cache_delay = 12
coherent = false
interleave_type = "stream"
interleave_param = 5

[bus]
full_duplex = true
bus_delay = 1
bus_width = 32
framing_time = 25
frame_size = 1

[dram]
dram_capacity = 65536
tick_per_clock = 1
ctrl_proc_time = 25
start_addr = 0
dram_config = "simplessd/config/PCIe4.cfg"
log_dir = "output"
