max_clock = 3000000
clock_granu = 1
log_level = "INFO"
log_name = "output/default.csv"
edges = [
    [
        "Requester",
        "DuplexBus",
    ],
    [
        "DuplexBus",
        "Snoop",
    ],
    [
        "Snoop",
        "DRAMsim3Interface",
    ],
]

[devices]
Requester = "Requester"
DRAMsim3Interface = "DRAMsim3Interface"
DuplexBus = "DuplexBus"
Snoop = "Snoop"

[Requester]
q_capacity = 32
cache_capacity = 8192
cache_delay = 12
issue_delay = 0
coherent = false
burst_size = 1
block_size = 64
interleave_type = "stream"
interleave_param = 5
trace_file = ""

[DRAMsim3Interface]
tick_per_clock = 1
process_time = 40
start = 0
capacity = 1073741824
rw_ratio = 0.5
config_file = "DRAMsim3/configs/DDR4_8Gb_x8_3200.ini"
output_dir = "output"

[DuplexBus]
is_full = true
half_rev_time = 100
delay_per_T = 1
width = 32
framing_time = 20
frame_size = 256

[Snoop]
line_num = 1024
assoc = 8
max_burst_inv = 8
ranges = [0, 1073741824]
eviction = "LRU"


