max_clock = 10000000
clock_granu = 1
log_level = "INFO"
log_name = "output/try.csv"
edges = [["aaa", "bbb"], ["bbb", "ccc"]]

[devices]
aaa = "Requester"
bbb = "DuplexBus"
ccc = "DRAMsim3Interface"

[aaa]
q_capacity = 32
cache_capacity = 8192
cache_delay = 12
issue_delay = 0
coherent = false
burst_size = 1
block_size = 64
interleave_type = "stream"
interleave_param = 500
trace_file = ""
